
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./users-client
      target: development
    command: npm run start
    volumes:
      - ./users-client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - backend
  backend:
    build:
        dockerfile: Dockerfile
        context: ./users-server
        target: development
    command: npm run start:dev
    env_file:
      - ./users-server/.env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./users-server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db