services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./users-client
      target: production
    ports:
      - 81:80
  backend:
    build:
      dockerfile: Dockerfile
      context: ./users-server
      target: production
    command: npm run start:prod
    env_file:
      - ./users-server/.env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./users-server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db